@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDgwODg0Nzh9._M5mG_PRyPMu-o_WVlPfvK1tXUjR1hh4y3WNGSTzanU

### Product index
GET http://localhost:3000/products

### Products Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "KFC Romance Novel"
}

### Products Show
GET http://localhost:3000/products/8

### Products Update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "name": "KFC Romance Novel"
}

### Products Destroy
DELETE http://localhost:3000/products/1



### Supplier Index
GET http://localhost:3000/supplier

### Supplier Show
GET http://localhost:3000/supplier/2

### Supplier Create
POST http://localhost:3000/supplier
Content-Type: application/json

{
  "name": "Amazon",
  "email": "amazon@test.com", 
  "phone_number": "(800)987-6543"}
}

### Supplier Update
PATCH http://localhost:3000/supplier/1
Content-Type: application/json

{
  "name": "Amazon"
}

### Supplier Delete
DELETE http://localhost:3000/supplier/1


### Image Index
GET http://localhost:3000/image

### Image Create

POST http://localhost:3000/image
Content-Type: application/json

{
  "url": "",
  "product_id": 
}




### User Create

POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Louise Belcher",
  "email": "louise@test.com",
  "password": "louise123",
  "password_confirmation": "louise123"
}


### Sessions Create

POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "ravioliravioli98"
}


### Photos create
POST http://localhost:3000/photos
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Test name",
  "width": 640,
  "height": 480
}


### Orders Create
POST http://localhost:3000/order
Authorization: Bearer {{jwt}}
Content-Type: application/json


{
  "product_id": "3",
  "quantity": "3"
}

### Orders Show
GET http://localhost:3000/order/1
Authorization: Bearer {{jwt}}

### Orders Index
GET http://localhost:3000/order
Authorization: Bearer {{jwt}}