### Product index
GET http://localhost:3000/products

### Products Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "KFC Romance Novel"
}

### Products Show
GET http://localhost:3000/products/8

### Products Update
PATCH http://localhost:3000/products/12
Content-Type: application/json

{
  "image_url": "https://hips.hearstapps.com/vader-prod.s3.amazonaws.com/1571683417-rubber-chicken-purse-1571683378.jpg?crop=1.00xw:0.667xh;0,0.168xh&resize=768:*"
}

### Products Destroy
DELETE http://localhost:3000/products/1



### Supplier Index
GET http://localhost:3000/supplier

### Supplier Show
GET http://localhost:3000/supplier/2

### Supplier Create
POST http://localhost:3000/supplier
Content-Type: application/json

{
  "name": "Walmart"
}

### Supplier Update
PATCH http://localhost:3000/supplier/1
Content-Type: application/json

{
  "phone_number": "(800)876-3456"
}

### Supplier Delete
DELETE http://localhost:3000/supplier/1