### Product index
GET http://localhost:3000/products

### Products Create
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "KFC Romance Novel"
}

### Products Show
GET http://localhost:3000/products/8

### Products Update
PATCH http://localhost:3000/products/3
Content-Type: application/json

{
  "name": "KFC Romance Novel"
}

### Products Destroy
DELETE http://localhost:3000/products/1



### Supplier Index
GET http://localhost:3000/supplier

### Supplier Show
GET http://localhost:3000/supplier/2

### Supplier Create
POST http://localhost:3000/supplier
Content-Type: application/json

{
  "name": "Walmart"
}

### Supplier Update
PATCH http://localhost:3000/supplier/1
Content-Type: application/json

{
  "name": "Amazon"
}

### Supplier Delete
DELETE http://localhost:3000/supplier/1


### Image Index
GET http://localhost:3000/image